# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import master_pb2 as master__pb2


class MasterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PassPointsToMapper = channel.unary_unary(
                '/MasterService/PassPointsToMapper',
                request_serializer=master__pb2.id.SerializeToString,
                response_deserializer=master__pb2.points.FromString,
                )
        self.PassMappersToReducers = channel.unary_unary(
                '/MasterService/PassMappersToReducers',
                request_serializer=master__pb2.id.SerializeToString,
                response_deserializer=master__pb2.mapperResponse.FromString,
                )


class MasterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PassPointsToMapper(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PassMappersToReducers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PassPointsToMapper': grpc.unary_unary_rpc_method_handler(
                    servicer.PassPointsToMapper,
                    request_deserializer=master__pb2.id.FromString,
                    response_serializer=master__pb2.points.SerializeToString,
            ),
            'PassMappersToReducers': grpc.unary_unary_rpc_method_handler(
                    servicer.PassMappersToReducers,
                    request_deserializer=master__pb2.id.FromString,
                    response_serializer=master__pb2.mapperResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MasterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MasterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PassPointsToMapper(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MasterService/PassPointsToMapper',
            master__pb2.id.SerializeToString,
            master__pb2.points.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PassMappersToReducers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MasterService/PassMappersToReducers',
            master__pb2.id.SerializeToString,
            master__pb2.mapperResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
