# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reducer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rreducer.proto\"1\n\x10partitionRequest\x12\x11\n\tpartition\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\"-\n\x11updated_centroids\x12\x18\n\x10updated_centroid\x18\x01 \x01(\t2K\n\x0eReducerService\x12\x39\n\x10RecievePartition\x12\x11.partitionRequest\x1a\x12.updated_centroidsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reducer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PARTITIONREQUEST']._serialized_start=17
  _globals['_PARTITIONREQUEST']._serialized_end=66
  _globals['_UPDATED_CENTROIDS']._serialized_start=68
  _globals['_UPDATED_CENTROIDS']._serialized_end=113
  _globals['_REDUCERSERVICE']._serialized_start=115
  _globals['_REDUCERSERVICE']._serialized_end=190
# @@protoc_insertion_point(module_scope)
